### ISSUE TITLE
Layout- title and body not aligned  

### ISSUE THREAD

**Issue by dsl89125** [strongliang/creadr#4]
creadr-main is on the left side of screen but the title is in the center of screen.
<img width="1460" alt="screen shot 2016-09-28 at 11 46 45 am" src="https://cloud.githubusercontent.com/assets/17232002/18927553/44837f34-8571-11e6-95cd-9cbca582ff56.png">

**Comment by strongliang** [comment]
will adjust that in the next version

**Comment by strongliang** [comment]
@dsl89125 which link is this article?

**Comment by dsl89125** [comment]
http://china.huanqiu.com/article/2016-09/9496231.html?from=bdwz

maybe its also relate to screen/browser size?
