### ISSUE TITLE
layout- paragraph is not separated (most of time)

### ISSUE THREAD

**Issue by dsl89125** [strongliang/creadr#5]
sometime paragraph is separated and most time not.

Left side is original web page ///// Right side is translated page

<img width="1216" alt="screen shot 2016-09-28 at 11 33 47 am" src="https://cloud.githubusercontent.com/assets/17232002/18927608/78aa6034-8571-11e6-96d5-9df8d063da3f.png">

**Comment by strongliang** [comment]
so the "责编：陈芳"  is missing?

**Comment by dsl89125** [comment]
oh, that missing is not a problem.

left side is original website, you see, its all different paragraphs. however, on the right side, the whole first part is a big block. it contains multiple paragraphs,  i think i will look better if its separated into different paragraphs like the original website.

**Comment by strongliang** [comment]
Currently there are two ways to extract the content, one is local, which is faster but the quality is lower; the other is via readability.com, which is much slower, but the quality is higher. For now I can use the 2nd one and see if I can find a better local method.

**Comment by strongliang** [comment]
https://github.com/strongliang/creadr/pull/9 should solve this, included in 0.2.0
