### ISSUE TITLE
Some website won't able to detect headers. 

### ISSUE THREAD

**Issue by dsl89125** [strongliang/creadr#7]
example http://edu.pcbaby.com.cn/314/3146266.html

steps to reproduce:
1: open this link: http://edu.pcbaby.com.cn/314/3146266.html
2: Look at title header 小猪照镜子
3: Click Creadr add-on, 
4: Article show up but no title (小猪照镜子)

actually every article from this website don't have title showing.

**Comment by strongliang** [comment]
https://github.com/strongliang/creadr/pull/9 should solve this, included in 0.2.0
